import React, { useState, useEffect } from "react";
import Markdown from "react-markdown";
import {
  FileText,
  Copy,
  Check,
  Volume2,
  VolumeX,
  Printer,
  ChevronDown,
  ChevronUp,
  Sparkles,
  BookOpen,
  ListOrdered,
  Lightbulb,
  Tag,
  Clock,
  FileCheck2,
  Search,
  ScanLine,
} from "lucide-react";
import { SummaryResult, AccessibilitySettings } from "../types";

interface SummaryCardProps {
  result: SummaryResult;
  settings: AccessibilitySettings;
  onReset: () => void;
}

export const SummaryCard: React.FC<SummaryCardProps> = ({
  result,
  settings,
  onReset,
}) => {
  const [copiedSection, setCopiedSection] = useState<string | null>(null);
  const [isSpeaking, setIsSpeaking] = useState(false);
  const [speechRate] = useState(1);
  const [showExtractedText, setShowExtractedText] = useState(false);
  const [searchTerm, setSearchTerm] = useState("");
  const isHighContrast = settings.highContrast;


  useEffect(() => {
    return () => {
      if (typeof window !== "undefined" && "speechSynthesis" in window) {
        window.speechSynthesis.cancel();
      }
    };
  }, []);

  const handleCopy = (text: string, sectionKey: string) => {
    navigator.clipboard.writeText(text);
    setCopiedSection(sectionKey);
    setTimeout(() => setCopiedSection(null), 2500);
  };

  const toggleSpeech = () => {
    if (typeof window === "undefined" || !("speechSynthesis" in window)) {
      return;
    }

    if (isSpeaking) {
      window.speechSynthesis.cancel();
      setIsSpeaking(false);
    } else {
      window.speechSynthesis.cancel();
      const textToRead = `${result.documentTitle}. Summary: ${
        result.summary
      }. Key Points: ${result.keyPoints.join(". ")}`;

      const utterance = new SpeechSynthesisUtterance(textToRead);
      utterance.rate = speechRate;
      utterance.onend = () => setIsSpeaking(false);
      utterance.onerror = () => setIsSpeaking(false);
      window.speechSynthesis.speak(utterance);
      setIsSpeaking(true);
    }
  };

  const handleDownload = (format: "txt" | "md" | "json") => {
    let content = "";
    let mimeType = "text/plain";
    const filename = `${result.fileName || "document"}_summary.${format}`;

    if (format === "json") {
      content = JSON.stringify(result, null, 2);
      mimeType = "application/json";
    } else if (format === "md") {
      content = `# ${result.documentTitle || result.fileName}\n\n` +
        `> **Document Type**: ${result.fileType.toUpperCase()} | **Tone**: ${result.documentTone || "Standard"}\n\n` +
        `## Executive Summary\n\n${result.summary}\n\n` +
        `## Key Points\n\n` +
        result.keyPoints.map((pt, i) => `${i + 1}. ${pt}`).join("\n") +
        `\n\n## Main Ideas & Conclusions\n\n` +
        result.mainIdeas.map((idea) => `- ${idea}`).join("\n") +
        (result.improvementSuggestions && result.improvementSuggestions.length > 0
          ? `\n\n## Improvement Suggestions & Next Steps\n\n` +
            result.improvementSuggestions.map((sug) => `- ${sug}`).join("\n")
          : "") +
        `\n\n---\n*Generated by Document Summary Assistant on ${new Date().toLocaleDateString()}*`;
      mimeType = "text/markdown";
    } else {
      content = `DOCUMENT SUMMARY: ${result.documentTitle || result.fileName}\n` +
        `=======================================================\n\n` +
        `SUMMARY:\n${result.summary}\n\n` +
        `KEY POINTS:\n` +
        result.keyPoints.map((pt, i) => `[${i + 1}] ${pt}`).join("\n") +
        `\n\nMAIN IDEAS:\n` +
        result.mainIdeas.map((idea) => `* ${idea}`).join("\n") +
        (result.improvementSuggestions && result.improvementSuggestions.length > 0
          ? `\n\nSUGGESTIONS:\n` +
            result.improvementSuggestions.map((sug) => `* ${sug}`).join("\n")
          : "");
    }

    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const filteredExtractedText = searchTerm.trim()
    ? result.extractedText
        .split("\n")
        .filter((line) =>
          line.toLowerCase().includes(searchTerm.toLowerCase())
        )
        .join("\n")
    : result.extractedText;

  return (
    <div
      id="summary-results-container"
      className={`rounded-2xl border transition-all overflow-hidden ${
        isHighContrast
          ? "bg-white border-black text-black"
          : "bg-white border-slate-200 modern-shadow text-slate-900"
      }`}
    >
     
      <div
        className={`p-6 sm:p-7 border-b ${
          isHighContrast
            ? "bg-slate-100 border-black"
            : "bg-gradient-to-r from-blue-50/80 to-slate-50 border-slate-200"
        }`}
      >
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div>
            <div className="flex flex-wrap items-center gap-2 mb-2">
              <span className="text-[11px] font-bold px-2.5 py-0.5 rounded-full uppercase tracking-wider bg-slate-800 text-white">
                {result.fileType.toUpperCase()}
              </span>
              {result.fileType === "image" && (
                <span className="text-[11px] font-bold px-2.5 py-0.5 rounded-full uppercase bg-emerald-100 text-emerald-800 border border-emerald-200 flex items-center gap-1">
                  <ScanLine className="w-3 h-3 text-emerald-700" />
                  OCR Transcribed
                </span>
              )}
              <span className="text-[11px] font-bold px-2.5 py-0.5 rounded-full uppercase bg-blue-100 text-blue-800 border border-blue-200">
                Length: {result.stats.summaryLength.toUpperCase()}
              </span>
              {result.documentTone && (
                <span className="text-[11px] font-medium px-2.5 py-0.5 rounded-full bg-white text-slate-700 border border-slate-200">
                  Tone: {result.documentTone}
                </span>
              )}
            </div>
            <h2
              id="summary-document-title"
              className="text-xl sm:text-2xl font-bold tracking-tight text-slate-900"
            >
              {result.documentTitle || result.fileName}
            </h2>
            <div className="flex flex-wrap items-center gap-3 text-xs text-slate-500 mt-2 font-medium">
              <span className="flex items-center gap-1.5 text-blue-600 font-semibold">
                <Clock className="w-3.5 h-3.5" />
                Est. Read Time: {result.stats.readingTimeMinutes} min
              </span>
              <span>•</span>
              <span>{result.stats.wordCount.toLocaleString()} words</span>
              <span>•</span>
              <span>{result.stats.characterCount.toLocaleString()} characters</span>
            </div>
          </div>

         
          <div className="flex flex-wrap items-center gap-2">
            <button
              id="btn-tts-read-aloud"
              type="button"
              onClick={toggleSpeech}
              className={`inline-flex items-center gap-1.5 px-4 py-2 rounded-lg font-semibold text-xs transition-all cursor-pointer shadow-2xs ${
                isSpeaking
                  ? "bg-red-600 text-white animate-pulse"
                  : isHighContrast
                  ? "bg-black text-white"
                  : "bg-blue-600 text-white hover:bg-blue-700"
              }`}
              title={isSpeaking ? "Stop voice readout" : "Listen to summary with voice synthesis"}
            >
              {isSpeaking ? (
                <>
                  <VolumeX className="w-4 h-4" />
                  <span>Stop Reading</span>
                </>
              ) : (
                <>
                  <Volume2 className="w-4 h-4" />
                  <span>Listen Aloud</span>
                </>
              )}
            </button>

            <button
              id="btn-copy-all-summary"
              type="button"
              onClick={() =>
                handleCopy(
                  `${result.documentTitle}\n\nSUMMARY:\n${result.summary}\n\nKEY POINTS:\n` +
                    result.keyPoints.map((k) => `• ${k}`).join("\n"),
                  "all"
                )
              }
              className={`inline-flex items-center gap-1.5 px-3.5 py-2 rounded-lg font-semibold text-xs border transition-all cursor-pointer ${
                copiedSection === "all"
                  ? "bg-blue-50 text-blue-700 border-blue-300"
                  : "bg-white text-slate-700 border-slate-300 hover:bg-slate-50 hover:text-slate-900"
              }`}
            >
              {copiedSection === "all" ? (
                <>
                  <Check className="w-3.5 h-3.5 text-blue-600" />
                  <span>Copied!</span>
                </>
              ) : (
                <>
                  <Copy className="w-3.5 h-3.5 text-slate-500" />
                  <span>Copy All</span>
                </>
              )}
            </button>
          </div>
        </div>
      </div>

      
      <div className="p-6 sm:p-8 space-y-7">
        {/* 1. SUMMARY SECTION */}
        <section id="section-document-summary" aria-labelledby="heading-summary">
          <div className="flex items-center justify-between pb-2.5 mb-3.5 border-b border-slate-200">
            <div className="flex items-center gap-2">
              <BookOpen className="w-5 h-5 text-blue-600" />
              <h3
                id="heading-summary"
                className="text-base sm:text-lg font-bold tracking-tight text-slate-900"
              >
                Executive Summary
              </h3>
            </div>
            <button
              type="button"
              onClick={() => handleCopy(result.summary, "summary")}
              className="text-xs font-semibold text-blue-600 hover:text-blue-700 hover:underline flex items-center gap-1 cursor-pointer"
            >
              {copiedSection === "summary" ? (
                <>
                  <Check className="w-3.5 h-3.5" /> Copied
                </>
              ) : (
                <>
                  <Copy className="w-3.5 h-3.5" /> Copy Summary
                </>
              )}
            </button>
          </div>

          <div
            className={`p-5 rounded-xl border leading-relaxed text-sm sm:text-base ${
              isHighContrast
                ? "bg-white border-black text-black"
                : "bg-slate-50 border-slate-200 text-slate-800"
            }`}
          >
            <div className="markdown-body space-y-3">
              <Markdown>{result.summary}</Markdown>
            </div>
          </div>
        </section>

        
        <section id="section-key-points" aria-labelledby="heading-key-points">
          <div className="flex items-center justify-between pb-2.5 mb-3.5 border-b border-slate-200">
            <div className="flex items-center gap-2">
              <ListOrdered className="w-5 h-5 text-blue-600" />
              <h3
                id="heading-key-points"
                className="text-base sm:text-lg font-bold tracking-tight text-slate-900"
              >
                Key Points & Main Takeaways
              </h3>
            </div>
            <button
              type="button"
              onClick={() =>
                handleCopy(
                  result.keyPoints.map((p, i) => `${i + 1}. ${p}`).join("\n"),
                  "keypoints"
                )
              }
              className="text-xs font-semibold text-blue-600 hover:text-blue-700 hover:underline flex items-center gap-1 cursor-pointer"
            >
              {copiedSection === "keypoints" ? (
                <>
                  <Check className="w-3.5 h-3.5" /> Copied
                </>
              ) : (
                <>
                  <Copy className="w-3.5 h-3.5" /> Copy Key Points
                </>
              )}
            </button>
          </div>

          <ul className="space-y-2.5">
            {result.keyPoints.map((point, idx) => (
              <li
                key={idx}
                className={`p-4 rounded-xl border flex items-start gap-3.5 transition-all ${
                  isHighContrast
                    ? "bg-white border-black text-black"
                    : "bg-blue-50/40 border-blue-100 text-slate-800 hover:bg-blue-50/70"
                }`}
              >
                <span
                  className={`shrink-0 w-6 h-6 rounded-md flex items-center justify-center text-xs font-bold ${
                    isHighContrast
                      ? "bg-black text-white"
                      : "bg-blue-600 text-white"
                  }`}
                >
                  {idx + 1}
                </span>
                <span className="text-sm sm:text-base font-normal leading-relaxed mt-0.5">
                  {point}
                </span>
              </li>
            ))}
          </ul>
        </section>

        
        {result.mainIdeas && result.mainIdeas.length > 0 && (
          <section id="section-main-ideas" aria-labelledby="heading-main-ideas">
            <div className="flex items-center gap-2 pb-2.5 mb-3.5 border-b border-slate-200">
              <Lightbulb className="w-5 h-5 text-blue-600" />
              <h3
                id="heading-main-ideas"
                className="text-base sm:text-lg font-bold tracking-tight text-slate-900"
              >
                Core Concepts & Conclusions
              </h3>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
              {result.mainIdeas.map((idea, idx) => (
                <div
                  key={idx}
                  className={`p-4 rounded-xl border ${
                    isHighContrast
                      ? "bg-white border-black text-black"
                      : "bg-slate-50 border-slate-200 text-slate-800"
                  }`}
                >
                  <p className="text-sm font-medium leading-relaxed">
                    💡 {idea}
                  </p>
                </div>
              ))}
            </div>
          </section>
        )}

       
        {result.improvementSuggestions &&
          result.improvementSuggestions.length > 0 && (
            <section
              id="section-improvement-suggestions"
              aria-labelledby="heading-suggestions"
            >
              <div className="flex items-center gap-2 pb-2.5 mb-3.5 border-b border-slate-200">
                <Sparkles className="w-5 h-5 text-blue-600" />
                <h3
                  id="heading-suggestions"
                  className="text-base sm:text-lg font-bold tracking-tight text-slate-900"
                >
                  Recommendations & Next Steps
                </h3>
              </div>
              <ul className="space-y-2">
                {result.improvementSuggestions.map((sug, idx) => (
                  <li
                    key={idx}
                    className={`p-3.5 rounded-xl border flex items-start gap-3 ${
                      isHighContrast
                        ? "bg-white border-black text-black"
                        : "bg-blue-50/30 border-blue-100 text-slate-800"
                    }`}
                  >
                    <span className="font-bold text-blue-600 text-sm">→</span>
                    <span className="text-sm leading-relaxed">{sug}</span>
                  </li>
                ))}
              </ul>
            </section>
          )}

        
        {result.topics && result.topics.length > 0 && (
          <div className="flex flex-wrap items-center gap-2 pt-1">
            <span className="text-xs font-semibold text-slate-500 flex items-center gap-1">
              <Tag className="w-3.5 h-3.5" /> Topics:
            </span>
            {result.topics.map((t, idx) => (
              <span
                key={idx}
                className="text-xs font-medium px-2.5 py-1 rounded-md border border-slate-200 bg-slate-50 text-slate-700"
              >
                #{t}
              </span>
            ))}
          </div>
        )}

       
        <section
          id="section-extracted-text"
          className="rounded-xl border border-slate-200 overflow-hidden bg-white"
        >
          <button
            type="button"
            onClick={() => setShowExtractedText(!showExtractedText)}
            aria-expanded={showExtractedText}
            className="w-full p-4 flex items-center justify-between font-semibold text-sm text-slate-800 bg-slate-50 hover:bg-slate-100/80 cursor-pointer transition-colors"
          >
            <div className="flex items-center gap-2">
              <FileCheck2 className="w-4 h-4 text-blue-600" />
              <span>
                {result.fileType === "image"
                  ? `View Raw OCR Transcription (${result.stats.wordCount.toLocaleString()} words extracted)`
                  : `View Raw Extracted Text (${result.stats.wordCount.toLocaleString()} words)`}
              </span>
            </div>
            {showExtractedText ? (
              <ChevronUp className="w-4 h-4 text-slate-500" />
            ) : (
              <ChevronDown className="w-4 h-4 text-slate-500" />
            )}
          </button>

          {showExtractedText && (
            <div className="p-4 border-t border-slate-200 bg-white space-y-3">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
                <div className="relative flex-1 max-w-sm">
                  <Search className="w-3.5 h-3.5 absolute left-3 top-2.5 text-slate-400" />
                  <input
                    type="text"
                    value={searchTerm}
                    onChange={(e) => setSearchTerm(e.target.value)}
                    placeholder="Search extracted text..."
                    className="w-full pl-8 pr-3 py-1.5 text-xs font-normal border border-slate-300 rounded-lg bg-slate-50 focus:bg-white focus:outline-none focus:border-blue-500"
                  />
                </div>
                <button
                  type="button"
                  onClick={() => handleCopy(result.extractedText, "raw")}
                  className="text-xs font-semibold text-blue-600 hover:text-blue-700 hover:underline flex items-center gap-1 cursor-pointer"
                >
                  {copiedSection === "raw" ? "Copied!" : "Copy Raw Text"}
                </button>
              </div>

              <pre className="p-3.5 rounded-lg border border-slate-200 max-h-72 overflow-y-auto font-mono text-xs whitespace-pre-wrap bg-slate-50 text-slate-800">
                {filteredExtractedText || "No text extracted."}
              </pre>
            </div>
          )}
        </section>

       
        <div className="pt-4 border-t border-slate-200 flex flex-col sm:flex-row sm:items-center justify-between gap-4 no-print">
          <div className="flex flex-wrap items-center gap-2">
            <span className="text-xs font-semibold text-slate-500">Download:</span>
            <button
              type="button"
              id="btn-download-txt"
              onClick={() => handleDownload("txt")}
              className="px-3 py-1.5 rounded-lg text-xs font-semibold border border-slate-300 bg-white text-slate-700 hover:bg-slate-50 hover:text-blue-600 hover:border-blue-300 transition-all cursor-pointer shadow-2xs"
            >
              .TXT
            </button>
            <button
              type="button"
              id="btn-download-md"
              onClick={() => handleDownload("md")}
              className="px-3 py-1.5 rounded-lg text-xs font-semibold border border-slate-300 bg-white text-slate-700 hover:bg-slate-50 hover:text-blue-600 hover:border-blue-300 transition-all cursor-pointer shadow-2xs"
            >
              .Markdown
            </button>
            <button
              type="button"
              id="btn-download-json"
              onClick={() => handleDownload("json")}
              className="px-3 py-1.5 rounded-lg text-xs font-semibold border border-slate-300 bg-white text-slate-700 hover:bg-slate-50 hover:text-blue-600 hover:border-blue-300 transition-all cursor-pointer shadow-2xs"
            >
              .JSON
            </button>
            <button
              type="button"
              id="btn-print-summary"
              onClick={() => window.print()}
              className="inline-flex items-center gap-1 px-3 py-1.5 rounded-lg text-xs font-semibold border border-slate-300 bg-white text-slate-700 hover:bg-slate-50 hover:text-blue-600 hover:border-blue-300 transition-all cursor-pointer shadow-2xs"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print</span>
            </button>
          </div>

          <button
            type="button"
            id="btn-summarize-another"
            onClick={onReset}
            className="px-5 py-2.5 rounded-xl font-semibold text-xs bg-blue-600 text-white hover:bg-blue-700 transition-all cursor-pointer shadow-xs"
          >
            Summarize Another Document
          </button>
        </div>
      </div>
    </div>
  );
};


